services:
    Grizzlylab\Bundle\DenyRoutesByEnvBundle\EventListener\DenyRoutesByEnvListener:
        arguments:
            - "@router"
            - "@translator"
            - "%kernel.environment%"
            - "%grizzlylab_deny_routes_by_env_config%"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }
